# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dra_pb2 as dra__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DRAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PowerOnMachine = channel.unary_unary(
                '/dra.DRAService/PowerOnMachine',
                request_serializer=dra__pb2.PowerOnRequest.SerializeToString,
                response_deserializer=dra__pb2.PowerOnResponse.FromString,
                _registered_method=True)
        self.PowerOffMachine = channel.unary_unary(
                '/dra.DRAService/PowerOffMachine',
                request_serializer=dra__pb2.PowerOffRequest.SerializeToString,
                response_deserializer=dra__pb2.PowerOffResponse.FromString,
                _registered_method=True)
        self.DeployApp = channel.unary_unary(
                '/dra.DRAService/DeployApp',
                request_serializer=dra__pb2.DeployRequest.SerializeToString,
                response_deserializer=dra__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.UndeployApp = channel.unary_unary(
                '/dra.DRAService/UndeployApp',
                request_serializer=dra__pb2.UndeployRequest.SerializeToString,
                response_deserializer=dra__pb2.UndeployResponse.FromString,
                _registered_method=True)
        self.GetMachineInfo = channel.unary_unary(
                '/dra.DRAService/GetMachineInfo',
                request_serializer=dra__pb2.Empty.SerializeToString,
                response_deserializer=dra__pb2.MachineInfoResponse.FromString,
                _registered_method=True)


class DRAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PowerOnMachine(self, request, context):
        """Turns on machine when connected
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOffMachine(self, request, context):
        """Turns off machine (e.g. on server interrupt)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployApp(self, request, context):
        """Deployment: consumes resources, gets GB from metadata store, unzips, calls psutil, updates DB state to ON
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeployApp(self, request, context):
        """Undeployment: frees resources used during deployment (GB, cores, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineInfo(self, request, context):
        """Gets machine info (CPU cores, GB) via psutil from current machine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DRAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PowerOnMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOnMachine,
                    request_deserializer=dra__pb2.PowerOnRequest.FromString,
                    response_serializer=dra__pb2.PowerOnResponse.SerializeToString,
            ),
            'PowerOffMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOffMachine,
                    request_deserializer=dra__pb2.PowerOffRequest.FromString,
                    response_serializer=dra__pb2.PowerOffResponse.SerializeToString,
            ),
            'DeployApp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployApp,
                    request_deserializer=dra__pb2.DeployRequest.FromString,
                    response_serializer=dra__pb2.DeployResponse.SerializeToString,
            ),
            'UndeployApp': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeployApp,
                    request_deserializer=dra__pb2.UndeployRequest.FromString,
                    response_serializer=dra__pb2.UndeployResponse.SerializeToString,
            ),
            'GetMachineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineInfo,
                    request_deserializer=dra__pb2.Empty.FromString,
                    response_serializer=dra__pb2.MachineInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dra.DRAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dra.DRAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DRAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PowerOnMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/PowerOnMachine',
            dra__pb2.PowerOnRequest.SerializeToString,
            dra__pb2.PowerOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PowerOffMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/PowerOffMachine',
            dra__pb2.PowerOffRequest.SerializeToString,
            dra__pb2.PowerOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/DeployApp',
            dra__pb2.DeployRequest.SerializeToString,
            dra__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeployApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/UndeployApp',
            dra__pb2.UndeployRequest.SerializeToString,
            dra__pb2.UndeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/GetMachineInfo',
            dra__pb2.Empty.SerializeToString,
            dra__pb2.MachineInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
